---
kind: pipeline
type: exec
name: default


platform:
  os: linux
  arch: amd64


steps:
- name: pull
  commands:
    - rm -rf /var/www/my-drone
    - cd /var/www/
    - git clone git@github.com:ironboxer/my-drone.git
    - cd my-drone
    - echo $(git log -1)
    - docker compose up -d --no-deps --build
  when:
    branch:
      - main


- name: check
  commands:
    - curl http://localhost:4444/


trigger:
  branch:
  - main
  - dev

