---
kind: pipeline
type: exec
name: default


platform:
  os: linux
  arch: amd64


steps:
- name: pull-image
  commands:
    - rm -rf /var/www/my-drone
    - cd /var/www/
    - git clone git@github.com:ironboxer/my-drone.git
    - cd my-drone
    - echo $(git log -1)
    - docker compose up --no-deps --force-recreate --build -d


- name: check-health
  commands:
    - sleep 1
    - curl http://127.0.0.1:4444/


trigger:
  branch:
  - main
  - dev

