---
services:
  web:
    user: root
    command: gunicorn app:app -b '0.0.0.0:4444'
    ports:
      - "4444:4444"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
      - NET_ADMIN
