---
services:
  web:
    user: root
    command: flask --app app run --host "0.0.0.0"
    ports:
      - "4444:5000"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
      - NET_ADMIN
